base_url:
  https://aaronwatts.dev
root:
  docs
home:
  home.html
sub_directories:
  guides
  tech
no_index:
  404.html
selectors:
  main:
    main
  title:
    h1
  intro:
    p#intro
  time:
    main > time
  img:
    main > img
  keywords:
    meta[name=keywords]
sitemap:
  path:
    sitemap.xml
rss:
  count: 10
feeds:
  all:
    path:
      feed.xml
    title:
      AaronWattsDev Latest
    href:
      https://aaronwatts.dev/feed.xml
    link:
      https://aaronwatts.dev/home
    description: >-
      The most recent content on AaronWattsDev
  guides:
    path:
      guides/feed.xml
    title:
      AaronWattsDev Guides
    href:
      https://aaronwatts.dev/guides/feed.xml
    link:
      https://aaronwatts.dev/guides
    description: >-
      The most recent guides on AaronWattsDev
  tech:
    path:
      tech/feed.xml
    title:
      AaronWattsDev Tech
    href:
      https://aaronwatts.dev/tech/feed.xml
    link:
      https://aaronwatts.dev/tech
    description: >-
      The most recent tech on AaronWattsDev
namespaces:
  sitemap:
    '':
      http://www.sitemaps.org/schemas/sitemap/0.9
  rss:
    atom:
      http://www.w3.org/2005/Atom
    media:
      http://search.yahoo.com/mrss/
    content:
      http://purl.org/rss/1.0/modules/content/
xsl:
  sitemap:
    /assets/styles/sitemap.xsl
  rss:
    /assets/styles/rss.xsl
